#!/bin/bash
#SBATCH --job-name=diamond
#SBATCH --output=rcc-%j.out 
#SBATCH --error=rcc-%j.err
#SBATCH --time=36:00:00 
#SBATCH --partition=gm4-pmext
#SBATCH --qos=gm4-cpu
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=40
#SBATCH --gres=gpu:0
#SBATCH --cpus-per-task=1 #increase this comensurate with number of threads
#SBATCH --mem-per-cpu=4000

WESTBINDIR=/home/jiaweiz/scratch-midway2/West/QEdir/bin/
NTASKS=$(($SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES))

# module load intel/19.1.1
# module load intelmpi/2019.up7+intel-19.1.1
# module load mkl/2020.up1
module unload intel intelmpi mkl
module load espresso/6.6+intelmpi-2018.2.199+intel-18.0
module load python/cpython-3.8.5

export I_MPI_PMI_LIBRARY=/software/slurm-current-$DISTARCH/lib/libpmi.so
export LD_LIBRARY_PATH=/software/python-3.8.5-el7-x86_64/lib:$LD_LIBRARY_PATH
export OMP_NUM_THREADS=1

srun -n ${NTASKS} ${WESTBINDIR}/pw.x     -N  $(($SLURM_JOB_NUM_NODES * 1)) -pd .true. -i pw.in    > pw.out
srun -n ${NTASKS} ${WESTBINDIR}/wstat.x  -ni $(($SLURM_JOB_NUM_NODES * 1)) -pd .true. -i wstat.in > wstat.out
srun -n ${NTASKS} ${WESTBINDIR}/wfreq.x  -ni $(($SLURM_JOB_NUM_NODES * 1)) -pd .true. -i wfreq.in > wfreq.out

